version: "3.8"
services:
  strapi:
    build: shoaibakhtar003/my-strapi-app:v1
    ports:
      - "1337:1337"
    volumes:
      - ./data:/srv/app/.tmp/data
    environment:
      NODE_ENV: "production"
